trigger:
  branches:
      include:
        - '*'

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python3 ./src/example_data_loading.py
  displayName: 'Try to save and load data'

- script: |
    cd ./tests && ./test.sh
  displayName: 'Try to run test'
